on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: "ubuntu-latest"
    name: Release for Pi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: "armv7-unknown-linux-musleabihf"
          args: "--locked --release"
          strip: true
      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snappwr
          path: "target/armv7-unknown-linux-musleabihf/release/snappwr"
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: "snappwr"
